-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtc5t8fv/n9biH4yU
BHqav9hwqgsjfFmH2admEYs1+qmgCgYIKoZIzj0DAQehRANCAATEfb+2v+AlhJoI
iRtvMIImhnzxLOZdAXv+Ch/OBrshkNh7Ejk2iwWS1MUgw22FwMLqI7RHFN60cqN+
MW4lhGiN
-----END PRIVATE KEY-----